name: CD Example Production
on:
    push:
        branches:
            - main


jobs:
  deploy:
    name: CD Example Production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout My Code
      uses: actions/checkout@4
    - name: SSH Connect
      uses: appleboy/ssh-action@1
      with:
         host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
              echo "Berhasil Konek ke Server"
          cd /home/yis
              ech

            if [ -d ".git" ]; then
              echo "📁 Repo exists, pulling latest changes..."

              # Update remote dengan token agar pull tidak butuh login
              git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/${{ secrets.GIT_USERNAME }}/cicd_database_example.git

              git pull origin main
            else
              echo "📥 Cloning repo for the first time..."
              git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com/${{ secrets.GIT_USERNAME }}/cicd_database_example.git .
            fi

            echo "✅ Deployment finished at $(date)"
